# Generated by Django 5.0.6 on 2024-05-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='population',
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='populationprojection',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
