# Generated by Django 5.0.6 on 2024-05-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0003_alter_population_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationprojection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
