# Generated by Django 5.0.6 on 2024-06-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0012_populationprojection_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('facility_type', models.CharField(max_length=20)),
                ('standard', models.IntegerField()),
                ('required', models.IntegerField()),
                ('new_need', models.IntegerField(blank=True, null=True)),
                ('suplus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'needs',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='NeedsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('water', 'Water'), ('sanitation', 'Sanitation')], max_length=50)),
                ('needs', models.ManyToManyField(related_name='needs', to='prms.needs')),
                ('population_projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.populationprojection')),
            ],
            options={
                'db_table': 'needs_assessment',
            },
        ),
        migrations.AlterField(
            model_name='mapprediction',
            name='needs_assestment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.needsassessment'),
        ),
        migrations.DeleteModel(
            name='NeedsAssestment',
        ),
    ]
