# Generated by Django 5.0.6 on 2024-07-17 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0017_equipmenttype_facilitytype_furnituretype_othertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.RemoveField(
            model_name='needsassessment',
            name='sector',
        ),
        migrations.AddField(
            model_name='needs',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prms.sector'),
        ),
        migrations.DeleteModel(
            name='MapPrediction',
        ),
    ]
