# Generated by Django 5.0.6 on 2024-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0018_sector_remove_needsassessment_sector_needs_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationprojection',
            name='is_education_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
