# Generated by Django 5.0.7 on 2024-08-10 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0020_needsassessment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCoordinatesAndAreaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=50)),
                ('area_name', models.CharField(max_length=50)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'facility_coordinates_and_area_name',
            },
        ),
        migrations.CreateModel(
            name='MapPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('facility_coordinates_and_area_name', models.ManyToManyField(related_name='facility_coordinates_and_area_name', to='prms.facilitycoordinatesandareaname')),
                ('needs_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.needsassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'map_prediction',
            },
        ),
    ]
