# Generated by Django 5.0.7 on 2024-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0021_facilitycoordinatesandareaname_mapprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapprediction',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
