# Generated by Django 5.1 on 2024-08-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0022_mapprediction_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_url', models.URLField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.district')),
            ],
            options={
                'db_table': 'town',
            },
        ),
    ]
