# Generated by Django 5.0.6 on 2024-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0004_populationprojection_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='populationprojection',
            old_name='population',
            new_name='projected_population',
        ),
        migrations.AddField(
            model_name='populationprojection',
            name='base_population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
