# Generated by Django 5.0.6 on 2024-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0005_rename_population_populationprojection_projected_population_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAndProjecting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_year', models.IntegerField()),
                ('projecting_year', models.IntegerField()),
                ('base_year_population', models.IntegerField()),
                ('projecting_year_population', models.IntegerField()),
            ],
            options={
                'db_table': 'base_and_projecting',
            },
        ),
        migrations.RemoveField(
            model_name='populationprojection',
            name='base_population',
        ),
        migrations.RemoveField(
            model_name='populationprojection',
            name='base_year',
        ),
        migrations.RemoveField(
            model_name='populationprojection',
            name='projected_population',
        ),
        migrations.RemoveField(
            model_name='populationprojection',
            name='projection_year',
        ),
        migrations.AddField(
            model_name='populationprojection',
            name='base_and_projecting',
            field=models.ManyToManyField(related_name='population_projections', to='prms.baseandprojecting'),
        ),
    ]
