# Generated by Django 5.0.6 on 2024-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0006_baseandprojecting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseAndProjecting',
            new_name='Projection',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='base_year_population',
            new_name='base_population',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='projecting_year_population',
            new_name='projecting_population',
        ),
        migrations.RemoveField(
            model_name='populationprojection',
            name='base_and_projecting',
        ),
        migrations.AddField(
            model_name='populationprojection',
            name='projections',
            field=models.ManyToManyField(related_name='projections', to='prms.projection'),
        ),
        migrations.AlterModelTable(
            name='projection',
            table='projection',
        ),
    ]
